package org.example.entity;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Getter;
import lombok.Setter;

import java.sql.Timestamp;
@Getter
@Setter
@TableName(value = "network_flow")
public class NetworkFlow {

  private Integer id;
  private long protocol;
  private String sourceIp;
  private long sourcePort;
  private String destinationIp;
  private long destinationPort;
  private  Timestamp timestamp;
  private long flowDuration;
  private long totalFwdPackets;
  private long totalBackwardPackets;
  private long totalLengthFwdPackets;
  private long totalLengthBwdPackets;
  private long fwdPacketLengthMax;
  private long fwdPacketLengthMin;
  private double fwdPacketLengthMean;
  private double fwdPacketLengthStd;
  private long bwdPacketLengthMax;
  private long bwdPacketLengthMin;
  private double bwdPacketLengthMean;
  private double bwdPacketLengthStd;
  private double flowBytesPerSec;
  private double flowPacketsPerSec;
  private double flowIatMean;
  private double flowIatStd;
  private double flowIatMax;
  private double flowIatMin;
  private double fwdIatTotal;
  private double fwdIatMean;
  private double fwdIatStd;
  private double fwdIatMax;
  private double fwdIatMin;
  private double bwdIatTotal;
  private double bwdIatMean;
  private double bwdIatStd;
  private double bwdIatMax;
  private double bwdIatMin;
  private long fwdPshFlags;
  private long bwdPshFlags;
  private long fwdUrgFlags;
  private long bwdUrgFlags;
  private long fwdHeaderLength;
  private long bwdHeaderLength;
  private double fwdPacketsPerSec;
  private double bwdPacketsPerSec;
  private long minPacketLength;
  private long maxPacketLength;
  private double packetLengthMean;
  private double packetLengthStd;
  private double packetLengthVariance;
  private long finFlagCount;
  private long synFlagCount;
  private long rstFlagCount;
  private long pshFlagCount;
  private long ackFlagCount;
  private long urgFlagCount;
  private long cweFlagCount;
  private long eceFlagCount;
  private double downUpRatio;
  private double averagePacketSize;
  private double avgFwdSegmentSize;
  private double avgBwdSegmentSize;
  private long fwdHeaderLengthEnd;
  private double fwdAvgBytesBulk;
  private double fwdAvgPacketsBulk;
  private double fwdAvgBulkRate;
  private double bwdAvgBytesBulk;
  private double bwdAvgPacketsBulk;
  private double bwdAvgBulkRate;
  private long subflowFwdPackets;
  private long subflowFwdBytes;
  private long subflowBwdPackets;
  private long subflowBwdBytes;
  private long initWinBytesForward;
  private long initWinBytesBackward;
  private long actDataPktFwd;
  private long minSegSizeForward;
  private double activeMean;
  private double activeStd;
  private double activeMax;
  private double activeMin;
  private double idleMean;
  private double idleStd;
  private double idleMax;
  private double idleMin;
  private long similarHttp;
  private long inbound;
  private String label;
}
